#include "bb_test_catalog.h"
#include <string.h>
const BBTestDefinition bb_tests[]={
{"rom-audit","Exact ROM audit","Validate SHA-256, mapper, sizes, and vectors.",1,0},
{"mmc1-selftest","MMC1 hardware-model self-test","Verify serial writes, PRG/CHR mapping, reset behavior, and consecutive-cycle write filtering.",1,0},
{"static-catalog","1.0.0 static catalog","Verify all 12,286 approved physical-bank contexts against the external ROM.",1,0},
{"direct-c-link","Generated direct-C link probe","Verify overlap-free physical-bank contexts compile and unknown contexts fail closed.",1,0},
{"control-contracts","1.0.0 control-contract verification","Verify scheduler continuations, mapper transfers, inline-pointer correction, and zero executable-RAM approval.",1,0},
{"semantic-cpu-smoke","Generated semantic CPU self-test","Verify fixed-context arithmetic, branches, stack calls, stores, and fail-closed misses.",1,0},
{"cold-boot-100-frames","Generated-static 100-frame cold boot","Run reset, NMI, DMA, PPU and APU activity for 100 deterministic NTSC frames.",1,0},
{"mods-framework","Music toolbar availability contract","Confirm Music is always available from the Launcher toolbar, opens the exact-ROM sound catalogue directly, and requires no Mods or Music Box menu entry.",1,0},
{"music-box-original-preview","Music Box original WAV preview","Render exact title and gameplay music plus pulse-1-isolated jump and bubble sound effects through proved sound-driver sequence triggers.",1,1},
{"music-box-36-entry-playback","Music Box full 36-entry playback catalogue","Confirm all exact-ROM Sound Select 00 through 35 entries appear in the Music Box using only their exact selector code labels, with original playback, Previous, Next, Restart, Stop, Loop, export, and replacement-preview controls.",1,0},
{"music-box-audio-conversion","Music Box Windows audio conversion","Use Windows Media Foundation to decode supported WAV, MP3, M4A, MP4, AAC, ADTS, and WMA input, then save a canonical mono 48 kHz signed 16-bit PCM WAV atomically before gameplay.",1,0},
{"music-box-replacement-wav","Music Box persistent replacement WAV","Convert supported Windows audio into the fixed per-selector PCM WAV, persist its source filename and enabled checkbox, preview it, and remove it without changing the ROM or generated C.",1,0},
{"music-box-live-replacement","Music Box live-game replacement hook","Preload an enabled selector WAV, suppress the matching exact-ROM sound dispatch, and mix replacement PCM with no trigger-time file access or runtime decoder.",1,0},
{"music-box-persistent-replacements","Music Box persistent replacement manifest","Confirm Sound Select 00 through 35 use fixed replacement filenames and persistent per-selector enabled values under the Music Box folder.",1,0},
{"frontend-keyboard","Keyboard and frontend contract","Check native controls, tab order, Enter activation, Escape close, Tools menu access, and labelled results.",1,0},
{"headed-test-workflow","Headed Test Centre workflow","Hide the Test Centre, show generated gameplay while a selected test runs, close gameplay, reopen Test Centre, and focus the results box.",1,0},
{"static-recomp-compliance","NES static-recomp compliance checklist","Validate the project against the build-time translation, physical-bank, fail-closed, deterministic, packaging and oracle requirements.",1,0},
{"whole-rom-code-data-certification","Whole-ROM code-versus-data certification","Verify all 131,072 PRG bytes have an evidence-backed code or non-code disposition with zero unknown bytes.",1,0},
{"semantic-data-family-certification","Semantic PRG data-family certification","Verify every classified PRG byte also belongs to a maintainable 1.0.0 semantic family, with exact item tables named separately from opaque non-code regions.",1,0},
{"special-item-table-contract","Exact special-item selector table contract","Verify the fifteen selector counters, threshold bytes, item codes, first three counter increment sites, and item-position table in the supplied ROM.",1,1},
{"natural-green-candy-selector","Natural Green Candy selector route","Use controller input only to blow at least 35 bubbles and prove selector index 1 naturally chooses item code $01.",1,1},
{"natural-blue-candy-selector","Natural Blue Candy selector route","Use controller input only to pop at least 35 bubbles and prove selector index 2 naturally chooses item code $03.",1,1},
{"natural-shoe-selector","Natural Shoe selector route","Use controller input only to bounce on at least 15 bubbles and prove selector index 3 naturally chooses item code $04.",1,1},
{"title-menu-exploration","Generated-static title and Play Select exploration","Render the title, press Start, move the cursor with Select, and verify deterministic frames.",1,1},
{"password-level5","NES Level 5 password route","Enter BIFFB through the normal password screen and start a stable one-player Level 5.",1,1},
{"one-player-basic","Round 1 movement, jump, and bubble","Start one-player mode normally and test controller-port-1 movement, jumping and bubble creation.",1,1},
{"two-player-basic","Two-player Round 1 controller-port test","Start two-player mode and independently exercise controller port 2.",1,1},
{"snapshot-resume","BBSNAP10 completed-frame restore","Save the full generated runtime including APU/DMC state, restore, resume, and match uninterrupted execution.",1,1},
{"level5-completion","Password Level 5 completion","Enter BIFFB, complete Level 5 with controller input, and verify stable Level 6.",1,1},
{"no-password-level1-to5","No-password Levels 1 through 5","Start 2P normally and play into stable Level 5 without passwords or RAM patches.",1,1},
{"audio-ten-second-sample","Ten-second Level 1 gameplay audio","Generate deterministic 48 kHz PCM from the NTSC APU during active Level 1 gameplay.",1,1},
{"password-level01-complete","Password Level 1 completion","Enter BBAAB in 2P mode and complete Level 1.",1,1},
{"password-level02-complete","Password Level 2 completion","Enter BAAAB in 2P mode and complete Level 2.",1,1},
{"password-level03-complete","Password Level 3 completion","Enter BABBI in 2P mode and complete Level 3.",1,1},
{"password-level04-complete","Password Level 4 completion","Enter BIIIB in 2P mode and complete Level 4.",1,1},
{"password-level05-complete","Password Level 5 completion, two players","Enter BIFFB in 2P mode and complete Level 5.",1,1},
{"password-level06-complete","Password Level 6 completion","Enter BFFFB in 2P mode and complete Level 6.",1,1},
{"password-level07-complete","Password Level 7 completion","Enter BFIIG in 2P mode and complete Level 7.",1,1},
{"password-level08-complete","Password Level 8 completion","Enter BJJJB in 2P mode and complete Level 8.",1,1},
{"password-level09-complete","Password Level 9 completion","Enter BJCCB in 2P mode and complete Level 9.",1,1},
{"password-level10-complete","Password Level 10 completion","Enter BCCCB in 2P mode and complete Level 10.",1,1},
{"password-level01-headed-graphics","Round 1 headed password screenshot","Enter BBAAB through the normal password screen, display Round 1 in the headed game window, and capture the visible window.",1,1},
{"password-level02-headed-graphics","Round 2 headed password screenshot","Enter BAAAB through the normal password screen, display Round 2 in the headed game window, and capture the visible window.",1,1},
{"password-level03-headed-graphics","Round 3 headed password screenshot","Enter BABBI through the normal password screen, display Round 3 in the headed game window, and capture the visible window.",1,1},
{"password-level04-headed-graphics","Round 4 headed password screenshot","Enter BIIIB through the normal password screen, display Round 4 in the headed game window, and capture the visible window.",1,1},
{"password-level05-headed-graphics","Round 5 headed password screenshot","Enter BIFFB through the normal password screen, display Round 5 in the headed game window, and capture the visible window.",1,1},
{"password-level06-headed-graphics","Round 6 headed password screenshot","Enter BFFFB through the normal password screen, display Round 6 in the headed game window, and capture the visible window.",1,1},
{"password-level07-headed-graphics","Round 7 headed password screenshot","Enter BFIIG through the normal password screen, display Round 7 in the headed game window, and capture the visible window.",1,1},
{"password-level08-headed-graphics","Round 8 headed password screenshot","Enter BJJJB through the normal password screen, display Round 8 in the headed game window, and capture the visible window.",1,1},
{"password-level09-headed-graphics","Round 9 headed password screenshot","Enter BJCCB through the normal password screen, display Round 9 in the headed game window, and capture the visible window.",1,1},
{"password-level10-headed-graphics","Round 10 headed password screenshot","Enter BCCCB through the normal password screen, display Round 10 in the headed game window, and capture the visible window.",1,1},
{"password-level11-headed-graphics","Round 11 headed password screenshot","Enter BCJJI through the normal password screen, display Round 11 in the headed game window, and capture the visible window.",1,1},
{"password-level12-headed-graphics","Round 12 headed password screenshot","Enter BGGGB through the normal password screen, display Round 12 in the headed game window, and capture the visible window.",1,1},
{"password-level13-headed-graphics","Round 13 headed password screenshot","Enter BGEEB through the normal password screen, display Round 13 in the headed game window, and capture the visible window.",1,1},
{"password-level14-headed-graphics","Round 14 headed password screenshot","Enter BEEEB through the normal password screen, display Round 14 in the headed game window, and capture the visible window.",1,1},
{"password-level15-headed-graphics","Round 15 headed password screenshot","Enter BEJJJ through the normal password screen, display Round 15 in the headed game window, and capture the visible window.",1,1},
{"password-level16-headed-graphics","Round 16 headed password screenshot","Enter AAAAB through the normal password screen, display Round 16 in the headed game window, and capture the visible window.",1,1},
{"password-level17-headed-graphics","Round 17 headed password screenshot","Enter AABBI through the normal password screen, display Round 17 in the headed game window, and capture the visible window.",1,1},
{"password-level18-headed-graphics","Round 18 headed password screenshot","Enter ABBBI through the normal password screen, display Round 18 in the headed game window, and capture the visible window.",1,1},
{"password-level19-headed-graphics","Round 19 headed password screenshot","Enter ABAAI through the normal password screen, display Round 19 in the headed game window, and capture the visible window.",1,1},
{"password-level20-headed-graphics","Round 20 headed password screenshot","Enter AFFFB through the normal password screen, display Round 20 in the headed game window, and capture the visible window.",1,1},
{"level1-item-ownership","Level 1 point and special-item ownership","Player 1 collects the round-clear point item and Player 2 collects the first natural special item.",1,1},
{"player1-special-item-agent","State-driven Player 1 special-item collection","Use live OAM coordinates and the exact ROM position code to reserve and collect the natural special item with Player 1, without RAM patches.",1,1},
{"special-item-trigger-contract","Exact-ROM special-item trigger contract","Capture the natural trigger commit counters, activation frame, pickup frame, owner, and position without changing RAM.",1,1},
{"player1-powerup-learning","Player 1 power-up collection learning","Run the best Player 1 item-position search and record whether a natural special item is collected without RAM patches.",1,1},
{"no-password-powerup-learning-1","No-password power-up learning attempt 1","Begin with deterministic item ownership and measure later level progress and survival.",1,1},
{"no-password-powerup-learning-2","No-password power-up learning attempt 2","Second item-assisted two-player learning policy.",1,1},
{"no-password-powerup-learning-3","No-password power-up learning attempt 3","Third item-assisted two-player learning policy.",1,1},
{"password-level99-entry","Round 99 password entry","Enter GEJJJ and verify a stable generated-static Round 99.",1,1},
{"password-level100-entry","Round A0 / decimal 100 password entry","Enter GJGEG and verify a stable generated-static Round 100.",1,1},
{"password-level100-cjgeg-compat","Conflicting CJGEG compatibility test","Enter the conflicting published A0 code and record the exact ROM rejecting it into Level 1.",1,1},
{"level99-secret-road-learning","Round 99 crystal and secret-road learning","Run a bounded two-player Round 99 attempt; progress is observational while static violations fail.",1,1},
{"password-level99-headed-graphics","Round 99 headed graphics capture","Enter GEJJJ in the generated X11/Win32 player and compare visible headed pixels with the generated framebuffer at six checkpoints.",1,1},
{"password-level100-headed-graphics","Round A0 headed graphics capture","Enter GJGEG in the generated X11/Win32 player and compare visible headed pixels with the generated framebuffer at six checkpoints.",1,1},
{"full-game-playability-certification","Full game ending and title-return certification","Require Round 99 completion, A0-to-final-boss progression, ending, and automatic return to the title screen without RAM patching or fallback.",1,1},
{"secret-level-select-eecjj","NES regular level-select secret","Enter EECJJ, select Continue, and verify A/B can change the starting round.",1,1},
{"secret-level-select-eecfg","NES Super level-select secret","Enter EECFG and verify the Super level-select entry path.",1,1},
{"hidden-secrets-plan","Hidden-secret acceptance plan","Review NES level select, Round 99 crystal, secret road, endings, life transfer, special-item thresholds, disputed codes, and the absence of ordinary secret rooms.",1,0},
{"active-audio-snapshot","Active PCM snapshot continuation","Save while audio synthesis is active, restore, and reproduce subsequent PCM sample for sample.",1,1},
{"ppu-checkpoint","State-aligned PPU checkpoint","Record palette frame, OAM, palette, nametable, scroll and timing hashes for independent oracle comparison.",1,1},
{"live-frontend","Live Windows and Linux frontend contract","Verify live generated video, two controller ports, bounded audio queue, pause, full screen, screenshots and BBSNAP10 keys are present.",1,1}
};
const size_t bb_test_count=sizeof(bb_tests)/sizeof(bb_tests[0]);
const BBTestDefinition*bb_test_find(const char*id){size_t i;for(i=0;i<bb_test_count;i++)if(strcmp(bb_tests[i].id,id)==0)return &bb_tests[i];return 0;}
