#include "bb_rom.h"
#include "bb_hash.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define EXPECTED_SHA "fc521e891d074369d67579fd56617460b9c9949dec67cc4a37d46b4e4bb09d29"
#define EXPECTED_PAYLOAD_SHA "31523322db8f94e7244f6e2d958692a412c1395fc744601d83d1e5111eff9042"
#define EXPECTED_CRC 0x5E900522u
static void seterr(char*out,size_t cap,const char*msg){size_t i=0;if(!out||!cap)return;while(msg[i]&&i+1<cap){out[i]=msg[i];i++;}out[i]=0;}
int bb_rom_load(const char*path,BBRom*r,char*error,size_t cap){FILE*f;long n;size_t got,off;uint8_t dig[32];memset(r,0,sizeof(*r));f=fopen(path,"rb");if(!f){seterr(error,cap,"cannot open ROM");return 0;}if(fseek(f,0,SEEK_END)!=0||(n=ftell(f))<16||fseek(f,0,SEEK_SET)!=0){fclose(f);seterr(error,cap,"cannot size ROM");return 0;}r->file_data=(uint8_t*)malloc((size_t)n);if(!r->file_data){fclose(f);seterr(error,cap,"out of memory");return 0;}got=fread(r->file_data,1,(size_t)n,f);fclose(f);if(got!=(size_t)n){bb_rom_free(r);seterr(error,cap,"short ROM read");return 0;}r->file_size=(size_t)n;if(memcmp(r->file_data,"NES\x1a",4)!=0){bb_rom_free(r);seterr(error,cap,"not an iNES ROM");return 0;}r->trainer=(r->file_data[6]&4)?1:0;r->battery=(r->file_data[6]&2)?1:0;r->mapper=(r->file_data[6]>>4)|(r->file_data[7]&0xf0);r->mirroring_vertical=(r->file_data[6]&1)?1:0;r->nes2=((r->file_data[7]&0x0c)==0x08)?1:0;r->prg_size=(size_t)r->file_data[4]*16384u;r->chr_size=(size_t)r->file_data[5]*8192u;off=16u+(r->trainer?512u:0u);if(off+r->prg_size+r->chr_size!=r->file_size){bb_rom_free(r);seterr(error,cap,"unexpected or truncated ROM length");return 0;}r->prg=r->file_data+off;r->chr=r->prg+r->prg_size;r->payload_size=r->prg_size+r->chr_size;if(r->prg_size<6){bb_rom_free(r);seterr(error,cap,"PRG too small for vectors");return 0;}r->nmi_vector=(uint16_t)(r->prg[r->prg_size-6]|((uint16_t)r->prg[r->prg_size-5]<<8));r->reset_vector=(uint16_t)(r->prg[r->prg_size-4]|((uint16_t)r->prg[r->prg_size-3]<<8));r->irq_vector=(uint16_t)(r->prg[r->prg_size-2]|((uint16_t)r->prg[r->prg_size-1]<<8));bb_sha256(r->file_data,r->file_size,dig);bb_hex(dig,32,r->sha256);bb_sha256(r->prg,r->payload_size,dig);bb_hex(dig,32,r->payload_sha256);r->payload_crc32=bb_crc32(r->prg,r->payload_size);seterr(error,cap,"");return 1;}
void bb_rom_free(BBRom*r){if(r&&r->file_data)free(r->file_data);if(r)memset(r,0,sizeof(*r));}
int bb_rom_is_expected(const BBRom*r,char*reason,size_t cap){if(strcmp(r->sha256,EXPECTED_SHA)!=0){seterr(reason,cap,"full-file SHA-256 does not match Bubble Bobble (USA) test ROM");return 0;}if(strcmp(r->payload_sha256,EXPECTED_PAYLOAD_SHA)!=0||r->payload_crc32!=EXPECTED_CRC){seterr(reason,cap,"PRG+CHR payload identity mismatch");return 0;}if(r->mapper!=1){seterr(reason,cap,"ROM is not mapper 1/MMC1");return 0;}if(r->prg_size!=131072u||r->chr_size!=32768u){seterr(reason,cap,"unexpected PRG or CHR size");return 0;}if(r->nmi_vector!=0xCE07u||r->reset_vector!=0xE882u||r->irq_vector!=0xCE61u){seterr(reason,cap,"interrupt vectors do not match expected ROM");return 0;}seterr(reason,cap,"exact expected Bubble Bobble (USA) ROM");return 1;}
int bb_rom_write_json(const BBRom*r,const char*path){FILE*f=fopen(path,"wb");char reason[160];int ok;if(!f)return 0;ok=bb_rom_is_expected(r,reason,sizeof(reason));fprintf(f,"{\n  \"format\": \"bubble-bobble-rom-audit-v1\",\n  \"file_size\": %llu,\n  \"sha256\": \"%s\",\n  \"payload_sha256\": \"%s\",\n  \"payload_crc32\": \"%08X\",\n  \"mapper\": %d,\n  \"board\": \"MMC1\",\n  \"prg_bytes\": %llu,\n  \"chr_bytes\": %llu,\n  \"mirroring\": \"%s\",\n  \"nmi_vector\": \"%04X\",\n  \"reset_vector\": \"%04X\",\n  \"irq_vector\": \"%04X\",\n  \"expected\": %s,\n  \"reason\": \"%s\"\n}\n",(unsigned long long)r->file_size,r->sha256,r->payload_sha256,r->payload_crc32,r->mapper,(unsigned long long)r->prg_size,(unsigned long long)r->chr_size,r->mirroring_vertical?"vertical":"horizontal",r->nmi_vector,r->reset_vector,r->irq_vector,ok?"true":"false",reason);fclose(f);return 1;}
